### ISSUE TITLE
Looking for count between x and y funtionality, i.e. a{x,y} in regexps

### ISSUE THREAD

**Issue by jgjl** [inhabitedtype/angstrom#110]
I am looking for a `count` function that accepts a range. Right now I use `many1` and then check the number of matched results after Angstrom did its thing. 
From the implementation of `count` I do not see a straightforward approach to implement this behavior. Any pointers on how this functionality could be implemented efficiently in Angstrom? Or is there a way to implement this behavior right now that I am not seeing?

**Comment by seliopou** [comment]
I haven't tested this code but you probably want something like this:

```ocaml
let rec at_most m p =
  if m = 0
  then return []
  else
    (lift2 (fun x xs -> x :: xs) p (at_most (m - 1) p))
    <|> return []
;;
      
let limits n m p =
  lift2 (fun xs ys -> xs @ ys)
    (count   n p)
    (at_most m p)
;;  
```

You can use `count` to implement the lower bound on the number of occurrences, and then implement something like `at_most` to take care of the upper bound.

Let me know if this was what you were looking for. Until then, closing.

**Comment by jgjl** [comment]
Thank you, the code works perfectly! 

Maybe other people would appreciate them being part of the Angstrom API, too :)
