### ISSUE TITLE
Honoring the license, 3-clause BSD

### ISSUE THREAD

**Issue by cfcs** [inhabitedtype/angstrom#134]
This library is licensed as BSD-3, which means you set some rules for some copyright disclaimers etc that must be reproduced.

This is my first time trying to follow the instructions in a copyright license, and it's already causing me lots of anxiety, but hoping to start distributing installable software packages that include Angstrom, I was wondering if you have any guidelines re: how to go about this, or can you link to an example OCaml package that provides a good example of where to put what?

**Comment by seliopou** [comment]
Hey thanks for the asking this question! Hopefully my answer will reduce your anxiety. IANAL but roughly speaking here's how I see folks adhere to the 3-clause BSD License. Just to be concrete I'll talk about Angstrom specifically.

```
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
```

This basically means that if you're redistributing Angstrom's *source code* the copyright headers in the source files must be maintained in your own source distribution. Typically folks will also distribute the LICENSE file itself, with some note that it applies to Angstrom's source code.

```
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
```

This means that if you're distributing a *binary*, the Angstrom's LICENSE file must accompany the binary distribution, and make reference to the fact that that particular license files comes from the Angstrom project.

```

3. Neither the name of the author nor the names of his contributors
   may be used to endorse or promote products derived from this software
without specific prior written permission.
```

This simply means, unless you get permission first, don't use the name Inhabited Type or the names of people listed (on the contributors page)[https://github.com/inhabitedtype/angstrom/graphs/contributors] page to promote your own project that's derived from or uses Angstrom. I've had people for permission in the past to use my name, typically for a blog post, and I believe I've mostly given permission. But regardless, the license says you must still ask. 

The first two points are, I believe, more or less common to almost all open-source licenses, in one form or another. The last one, to my knowledge, isn't a common condition.

Hope this helps!
