### ISSUE TITLE
Help with using the buffered interface (or how do I parse the same input less times)?

### ISSUE THREAD

**Issue by loxs** [inhabitedtype/angstrom#135]
I am a newbie to parsers and OCaml and sorry if this a stupid question, but I can't seem to grok it by reading the source.

I have a string of this kind `2018-03-23 something1 something2 ...`
I want to try to parse a date, if that succeeds, try several possibilities for `something1`, if that succeeds try several possibilities for `something2` etc.

Initially I had parser of this kind and it works:

```
  choice [
    list [date; whitespace; something1; whitespace; something2_variant1];
    list [date; whitespace; something1; whitespace; something2_variant2]; 
    list [date; whitespace; something1; whitespace; something2_variant3];
    list [date; whitespace; something1;];
    list [date;];
   ]
```
Everyone can imagine how this becomes tedious very fast and I also presume that it's very slow, as it has to walk the whole string many times in order to find some of the later variants.
So I decided to use the buffered interface, as (I guess) it probably can parse something from the beginning, then allow me to check conditions, then proceed with what I instruct it.

So I'm trying to do something like this: 

```ocaml
  match Buffered.feed (Buffered.parse  date) input with
  | Buffered.Done ({buf=unconsumed_buf; off = off; len = len}, consumed) ->
    Buffered.feed (Buffered.parse whitespace) (`Bigstring unconsumed_buf)
  | any -> any (* we'll try other things if we fail *)
```

But this fails to parse whitespace after successfully parsing the date. I guess what happens is that it starts again from the beginning of the input. What should I call in order to proceed with another parser, from where I am upon success/failure?

Of course, other suggestions for solving my problem are also welcome. I might be completely wrong with my presumptions (I might not need the Buffered module at all)

Here are my implementations of `date` and `whitespace`:

```ocaml
let date =
  take_while (function | '0'..'9' -> true | '-' -> true | _ -> false)
  >>= fun date_string ->
  try return (`Date (Core_kernel.Date.of_string date_string))
  with _ ->
    let error_msg = format_of_string "Failed to parse a date from: %s" in
    fail (Format.asprintf error_msg date_string)

let is_whitespace c =
  match c with
  | '\x20' | '\x0a' | '\x0d' | '\x09' -> true
  | _ -> false

let whitespace =
  take_while is_whitespace
  >>= function
  | "" -> fail "Expected whitespace"
  | _ -> return `Whitespace
```

**Comment by loxs** [comment]
I got an answer from @seliopou here: https://discuss.ocaml.org/t/angstrom-parser-optimization/1754/2
It solves my bigger problem in how to write my parser and really helped me to start understanding what's it all about.
Still I'll leave this issue, as I didn't manage to make the Buffered interface work. I'd love to get that answered too.

**Comment by seliopou** [comment]
It looks like you're not taking into account the `off` and `len` that's returned in the `unconsumed` result. Try using

```ocaml
let new_input = Bigstring.sub ~off ~len unconsumed_buf
```
and see what happens.
