### ISSUE TITLE
choice combinator does not propagate errors

### ISSUE THREAD

**Issue by loxs** [inhabitedtype/angstrom#136]
Seems like where I use the `choice` combinator, if an error happens I just get something like:

```ocaml
Result.Error ":: satisfy"
```

This happens even if I send a proper error from below. When I test my leaf parsers I get it reported properly. I understand it means "all of these parsers failed", but wouldn't it be better if we could get all the errors or at least the last one or something?

**Comment by dinosaure** [comment]
The [`<?>`](https://github.com/inhabitedtype/angstrom/blob/master/lib/angstrom.mli#L321) could be help you and refines where your parser fails.

**Comment by loxs** [comment]
Uhm, excuse me if I'm wrong, but I already know it and use it, but in the case of `choice` combinator it does not seem to propagate errors. I'll try to come up with a minimal example.

**Comment by loxs** [comment]
Here it is:

```ocaml
utop # Angstrom.parse_string (choice [char 'a' <?> "a required";  char 'b' <?> "b required"]) "c";;
- : (char, string) result = Result.Error ": empty"
```

**Comment by dinosaure** [comment]
Ah, I see so if you want to handle as an error an something else of than a parser `p`, you should write:

```
parse_string (choice [ char 'a'; char 'b' ] <|> (fail "my-error")) "c";;
```

to catch the _ else_ case.

**Comment by loxs** [comment]
That kind of half solves my problem. I would still love to have the actual error the last of the tried parsers produced.

**Comment by seliopou** [comment]
You can use the `commit` parser to, well, commit to the current parse. If you ever try to backtrack past the last committed position in the input, the error will just get propagated to the top. I think that, combined with an optional argument to `choice` to supply an error message besides `"empty"`, would solve your problem.
