### ISSUE TITLE
No usage example of commit

### ISSUE THREAD

**Issue by loxs** [inhabitedtype/angstrom#144]
I can't figure out how to use `commit`
For example, I have this parser

```ocaml
choice  [ string "@@" *> whitespace *> parser1 ;
                string "@" *> whitespace *> parser2 ]
```

How do I instruct it to commit after it has successfully parsed either "@@" or "@"?

**Comment by seliopou** [comment]
You'd just put the `commit` after "@@" or "@":

```ocaml
choice  [ string "@@" *> commit *> whitespace *> parser1
        ; string "@"  *> commit *> whitespace *> parser2 ]
```

You can also implement this without choice with a little bit of lookahead:

```ocaml
char '@' 
*>  peek_char_fail
>>= function
  | '@' -> any_char *> whitespace *> parser1
  | _   -> whitespace *> parser2
```

**Comment by loxs** [comment]
Alright, but then it means that `commit` is not working.
My understanding is that it should cause the individual parser errors to show up, but I still get the generic `choice` error:

```ocaml
utop # let test =
choice  [ string "@@" *> commit *> (char '*' <?> "Expected *")
        ; string "@"  *> commit *> (char '!' <?> "Expected !")];;
val test : char t = <abstr>

utop # parse_string test "@@^";;
- : (char, string) result = Result.Error ": no more choices"
```

(I am aware of your second suggestion, but my actual example is a lot more complex than that, so I've dumbed it down for the sake of example)
