### ISSUE TITLE
Windows Support - Symlink issues

### ISSUE THREAD

**Issue by bryphe** [inhabitedtype/angstrom#152]
First off, thanks for your work on angstrom!

We are currently using angstrom with `esy` - https://github.com/esy/esy - and working on adding Windows support. 

One issue we have at the moment is an issue installing this library on Windows. We get this error message:
```
error command failed: "tar" "xf" "/cygdrive/c/Users/appveyor/AppData/Local/Temp/1/esy-6bb76a/0.10.0.tar.gz" "-C" "/cygdrive/c/Users/appveyor/AppData/Local/Temp/1/esy-7d621f"
      stderr:
               tar: angstrom-0.10.0/examples/http.ml: Cannot create symlink to ‘rFC2616.ml’: No such file or directory
               tar: angstrom-0.10.0/examples/json.ml: Cannot create symlink to ‘rFC7159.ml’: No such file or directory
               tar: Exiting with failure status due to previous errors
```

Our extraction on Windows fails both in the `examples` and `benchmarks` folder. I'm wondering if you'd be open to using an alternative to symlinks here - like the `copy_files` stanza in dune / jbuilder?

Symlinks have some problematic cases on Windows (you have to be running as an administrator to create them, by default!), and then have further issues in our cygwin layer as above.

**Comment by hcarty** [comment]
A dune fix seems reasonable in this case.  It can make development/editing a bit of a pain since the file isn't there in the main source tree, but it may be a reasonable trade-off for proper Windows compatibility.

Do you think you'd have time to put a PR together @bryphe?

**Comment by bryphe** [comment]
Thanks for the reply, @hcarty ! Sure, I can put a PR together for this.

**Comment by bryphe** [comment]
Thanks @hcarty for bringing this in!
