### ISSUE TITLE
An error type

### ISSUE THREAD

**Issue by dinosaure** [inhabitedtype/angstrom#160]
It's a possible improvement of `angstrom` which will use an open variant `type error += ..` to let the user to define his errors (by this way `type Angstrom.error += My_error of with_some_values`). I don't know about any regression on performances in this case but it could be interesting from the user's point of view to have precise ADT instead a `string`.

Then, it's much more the API and we should provide some explanations if we want to integrate it, like how to use it and show some bad patterns.

I'm ok with both but a discussion could be interesting on specific topic.

**Comment by seliopou** [comment]
I'm not too keen on adding features to the library that depend on, as far as I can tell, not widely known or understood feature of the type system. Maybe if open variants get more traction, it can be considered again.
