### ISSUE TITLE
unbox Parser.t

### ISSUE THREAD

**Issue by thedufer** [inhabitedtype/angstrom#175]
Marking the single-field record type `'a Parser.t` with `[@@unboxed]` should shrink its memory footprint.

**Comment by thedufer** [comment]
A naive attempt at this somehow made things much worse.  Going to get some input on this, but it might be a dead end.

**Comment by thedufer** [comment]
After some investigating, it looks like the unboxing causes the compiler to unnecessarily insert some closure allocations into functions like `choice` and `count`.  smuenzel has a a minimal-ish case that exhibits this behavior (both with and without flambda, tested only on 4.08) and is investigating.  He thinks this is a compiler bug.

Until we figure this out, though, unboxing is just clearly a mistake.

**Comment by dinosaure** [comment]
From investigation of @chambart and @gasche, `unbox` just consider parsers as functions and, in the current stage of `angstrom` it seems that functions produced have too many arguments. I reached the same conclusion in my different branches on my local fork.

**Comment by thedufer** [comment]
The simple version of the problem is that if your core type is a function (as an unboxed parser is):

```
type t = a -> b -> c
```

and you have a function to construct one:

```
val create : d -> t
```

Then this can, depending on the implementation, be collapsed to a single function of type `d -> a -> b -> c`, which means that calling `create` is a partial function application and requires a closure allocation.  I think we can avoid this by wrapping every construction of a parser in `Sys.opaque_identity`, but this seems awfully easy to get wrong so even it it works that isn't a very compelling plan.  I'm going to try this out and see if it works, and if so whether the performance benefits are significant.

The optimization that performs this function combination seems to be in question, so there's also a chance that it'll be dropped.

Credit to @lpw25 for explaining what is going on here.

**Comment by seliopou** [comment]
I think that the conclusion here is that there isn't a performance benefit in the current version of the compiler. That might change in the future, but for now I don't think this issue is actionable.

Closing until a compiler exists that will speed up the library.
