### ISSUE TITLE
Angstrom_unix.parse will fail on completely parsed files

### ISSUE THREAD

**Issue by hcarty** [inhabitedtype/angstrom#19]
The `assert` at https://github.com/inhabitedtype/angstrom/blob/master/unix/angstrom_unix.ml#L49 will trigger if the `in_channel` is fully parsed.

**Comment by seliopou** [comment]
Do you have an example that exhibits this behavior? `state_to_unconsumed` only returns `None` if given a `Partial` state, and the parse loop should never return a `Partial` state.

**Comment by hcarty** [comment]
I'm working on a msgpack implementation using Angstrom that hit this against a test file.  It's not quite ready for release but I'll try to create a minimal test case.

**Comment by seliopou** [comment]
That would be much appreciated!

**Comment by hcarty** [comment]
I may be able to come up with something better, but under 4.02.3 + latest Angstrom from master as of an hour or two ago this will `assert` for me:

```ocaml
open Angstrom

type t =
  | Nil

let byte x = char @@ Char.chr x

let nil =
  byte 0xc0 *> return Nil

let nils =
  many nil

let () =
  let file = "nils.msgpack" in
  let oc = open_out_bin file in
  output_char oc (Char.chr 0xc0);
  output_char oc (Char.chr 0xc0);
  close_out oc;
  let ic = open_in_bin "nils.msgpack" in
  let _ = Angstrom_unix.parse nils ic in
  close_in ic
```

Parsing a one byte file with `nil` doesn't fail but parsing with `nils` does.

Thanks for taking a look at this!

**Comment by seliopou** [comment]
[Recursive calls are very important](https://github.com/inhabitedtype/angstrom/blob/master/unix/angstrom_unix.ml#L42-L43). I'll push a fix for this shortly. Thanks for reporting it.

**Comment by hcarty** [comment]
Thanks for the quick fix!
