### ISSUE TITLE
add notFollowedBy or other negation combinator

### ISSUE THREAD

**Issue by arbipher** [inhabitedtype/angstrom#201]
There is `not_char` in the API but I wonder is it possible to add another combinator for negation. I found [`notFollowedBy`](https://hackage.haskell.org/package/parsec-3.1.14.0/docs/Text-Parsec-Combinator.html#v:notFollowedBy) in Parsec.

In my case, I need a `not_string` whichI can implement a custom function. I wonder if a universal negation combinator is possible.

**Comment by thedufer** [comment]
If I've understood your meaning, you can construct `not_string` as follows:

    let not_string str =
      string str >>| const false <|> return true >>= function
      | true -> return ()
      | false -> fail "not_string"

This will fail if the next string matches the argument, and otherwise succeed having consumed no input.

I think you can generally use that construct for negative lookahead:

  let not_followed_by p =
    p >>| const false <|> return true >>= function
    | true -> return ()
    | false -> fail "not_followed_by"

**Comment by arbipher** [comment]
Cool!

My original post is vague but your answer is illustrative for my questions.

The key part is to use `const false` (instead `fail _` in my previous attempts).

**Comment by thedufer** [comment]
@seliopou What do you think about adding this `not_followed_by` combinator?  I suspect it can be implemented more nicely internally.
