### ISSUE TITLE
Implement parsers for ints of various bit widths

### ISSUE THREAD

**Issue by seliopou** [inhabitedtype/angstrom#22]
These parsers should take into account endianness, or at least convey the assumed endianness via its name. This could be in the form of a submodule (e.g., `LE`, `BE`) or via a parser name suffix (e.g., `int8_le`, `int32_be`, etc.).

**Comment by hcarty** [comment]
I have some of these implemented already if you're interested. I'm currently using ocplib-endian for the conversion from bytes to integers. This isn't an additional dependency for now since cstruct uses it. Is that still an OK dependency given #1?

**Comment by seliopou** [comment]
Closed by #23.
