### ISSUE TITLE
Safe handling of unsigned int32/64

### ISSUE THREAD

**Issue by darioteixeira** [inhabitedtype/angstrom#33]
It would be nice to be able to handle unsigned int32 and int64 numbers properly, perhaps using the [ocaml-stdint](https://github.com/andrenth/ocaml-stdint) library or similar. Are there any such plans?

**Comment by hcarty** [comment]
I initially used ocaml-stdint for the patch.  Unfortunately I ran into a handful of issues along the way and moved away from it (andrenth/ocaml-stdint#7, andrenth/ocaml-stdint#8).  I haven't had time to look into proper patches and tests for ocaml-stdint.

I also posted a feature request to OCaml Mantis to add unsigned 32bit and 64bit integer support which would be worth using if/when that lands (http://caml.inria.fr/mantis/view.php?id=7280)

**Comment by darioteixeira** [comment]
Those bugs in ocaml-stdint are indeed unfortunate, but did you get the feeling the project is stale and they won't get fixed soon?  And yes, I agree that ideally one would have Uint32 and Uint64 shipped with the stdlib, but I reckon that may take a while...

**Comment by seliopou** [comment]
There are no such plans at the moment. And given that:

1. @hcarty had previously explored using ocaml-stdint and decided against it;
2. there are some pretty bad outstanding bugs in ocaml-stdint;
3. there are multiple libraries that provide unsigned integer types, none of which seem to be well-adopted or maintained, including stdint despite its name; and
4. users can use existing parsers to surface bits in a form that stdint or some other such library understands and perform the conversions manually (e.g., `BE.int32 >>| Stdint.UInt32.of_int32`, or something involving `Stdint.UInt32.of_bytes_{little,big}endian`) at their own peril

It is unlikely that support for unsigned int types will be incorporated in the short- to medium-term. Long-term, I would support a push to get an unsigned int type into the standard library, with an OPAM package providing support for previous compiler versions similar to the [result](http://opam.ocaml.org/packages/result/) package.

As a side note, it's unfortunate that (3) is an issue, as most of these libraries use equivalent representations (i.e., signed ints) but keep the the types abstract.
