### ISSUE TITLE
RFC: Cstruct as exclusive input type for the Unbuffered interface

### ISSUE THREAD

**Issue by seliopou** [inhabitedtype/angstrom#44]
I'm contemplating a change to the `Unbuffered` API that would eliminate `string` as a valid input type. Instead, all input to the `Unbuffered` interface would take the form of a `bigstring` or s `Cstruct.t`:

``` ocaml
val parse : ?input:[`Cstruct of Cstruct.t | `Bigstring of bigstring ] -> 'a t -> 'a state
```

The `Buffered` interface would still allow string inputs, as well as `parse_only`.

This change would greatly simplify the implementation, and likely speed it up a bit. Currently, retrieving bytes from the input must match on the input type and dispatch to `bigstring` or `string` operations appropriately. That would go away. This change would also make for the API proposed in #40 conceptually cleaner, as there is no question as to whether the buffer Angtrom returns was freshly allocated or not. To be clear, it would not be.

The downside is that parsing a string will now always require a copy. This is less efficient, but one could argue that if you're doing IO in OCaml via strings, you're already being inefficient.

Questions or comments would be greatly appreciated.

**Comment by hcarty** [comment]
This, along with a way to get a sub(cstruct|bigstring) while parsing, seems like it could significantly speed up `take`-like operations with large payloads.

How expensive is a `string` to `string` copy vs a `Cstruct.t` to `string` copy?

**Comment by yallop** [comment]
It'd be interesting to see some numbers, to get a better idea of the potential performance benefits.

>  Currently, retrieving bytes from the input must match on the input type and dispatch to bigstring or string operations appropriately. That would go away. 

Would it be possible to lift the choice between `string` and `bigarray` to the top level, so that the match occurs only once rather than on each operation?

**Comment by seliopou** [comment]
@yallop performance isn't the only reason I'd like to do this, but your point is still very much a valid one. Here's a before and after for the `json` and `http` benchmarks. Before is the current master, and After uses a record containing the operations that the `Input` module needs for each input buffer type. The record closes over the input buffer, so dispatch is done once during input feeding, and the rest of the code doesn't need to know anything about the different input buffer types.

Before:
```
┌──────┬──────────┬──────────┬───────────────┬─────────┬──────────┬──────────┬────────────┐
│ Name │ Time R^2 │ Time/Run │          95ci │ mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────┼──────────┼──────────┼───────────────┼─────────┼──────────┼──────────┼────────────┤
│ json │     1.00 │  11.20ms │ -0.66% +0.73% │  3.75Mw │ 190.97kw │ 190.97kw │     53.68% │
│ http │     1.00 │  20.85ms │ -0.67% +0.81% │  8.19Mw │  53.03kw │  53.03kw │    100.00% │
└──────┴──────────┴──────────┴───────────────┴─────────┴──────────┴──────────┴────────────┘
```

After:
```
┌──────┬──────────┬──────────┬───────────────┬─────────┬──────────┬──────────┬────────────┐
│ Name │ Time R^2 │ Time/Run │          95ci │ mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────┼──────────┼──────────┼───────────────┼─────────┼──────────┼──────────┼────────────┤
│ json │     1.00 │  11.05ms │ -0.73% +0.80% │  3.75Mw │ 190.97kw │ 190.97kw │     50.67% │
│ http │     1.00 │  21.80ms │ -0.58% +0.66% │  8.19Mw │  53.10kw │  53.10kw │    100.00% │
└──────┴──────────┴──────────┴───────────────┴─────────┴──────────┴──────────┴────────────┘
```

The confidence intervals don't overlap, so I'm taking this as a performance regression. Is it worth trying first class modules, or otherwise eliminating the closure creation?

**Comment by yallop** [comment]
@seliopou: Thanks for the interesting performance  numbers.  I'd be interested to have a closer look.  Are you able to share your benchmark code (privately, if you prefer)?

**Comment by seliopou** [comment]
@yallop not a problem! You can find the code [here](https://github.com/inhabitedtype/angstrom/tree/record_inputs).
