### ISSUE TITLE
tutorial introduction/wiki?

### ISSUE THREAD

**Issue by ds2643** [inhabitedtype/angstrom#59]
What resource(s) do you suggest to folks who would like to learn to use Angstrom?

**Comment by seliopou** [comment]
For now the resources available are the [mli documentation](https://github.com/inhabitedtype/angstrom/blob/master/lib/angstrom.mli), the examples in the [rfcs](https://github.com/inhabitedtype/angstrom/tree/master/rfcs) subdirectory, and the [benchmarks](https://github.com/inhabitedtype/angstrom/tree/master/benchmarks). 

In terms of using parser combinator libraries in general, any tutorial on the subject should translate well to the library.

Is there anything in particular you were looking for?

**Comment by ds2643** [comment]
Thanks for the response. Do you suggest a particular text on the subject that you found useful in your implementation?

**Comment by seliopou** [comment]
Nope, just knowledge of various other implementations and the general concepts.

Closing this, but feel free to continue discussion.
