### ISSUE TITLE
Counting characters in a file.

### ISSUE THREAD

**Issue by pveber** [inhabitedtype/angstrom#60]
Trying to get a feeling of how `angstrom` works, I started with the task of counting the number of characters in a file. I'm writing this:
```ocaml
open Angstrom

let rec item accu =
  (end_of_input >>= fun () -> return accu) 
  <|> 
  (any_char >>= fun _ -> item (accu + 1))

let n = parse_only (item 0) (`String "123456")
```
It seems to work but I'm wondering if I'm using the library in a proper (and efficient) way.

**Comment by seliopou** [comment]
Looks like your implementation should do what you intended it to do. Here's how I would do it:

```ocaml
let count_chars () =
  let len = ref 0 in
  skip_while (fun _ -> incr len; true) *> end_of_input
  >>| fun () -> !len
```

This of course uses state, which may be a turnoff to some, but it has several virtues:

* it does not use backtracking and therefore does not allocate failure continuations;
* `skip_while` will iterate over available input in a tight loop; and
* it only allocates three parser values, whereas yours will allocate intermediate parser values in proportion to the input size.

All of this only really matters for performance-sensitive code. If that's not a concern then I'd just run with your solution, though there is one tweak I'd make:

```ocaml
let rec count_chars acc =
  at_end_of_input
  >>= function
    | true  -> return acc
    | false -> any_char *> count_chars (acc + 1)
```

This eliminates the backtracking by using `at_end_of_input` and matching against the result. It's also a bit clearer to use the `*>` operator to indicate that you don't care about the result.

Closing the issue but feel free to continue discussion.

**Comment by pveber** [comment]
Thanks for the detailed answer Spiros! Your version with side-effects does yield a very significant speed improvement (about 10 times faster in my toy bench).
