### ISSUE TITLE
Folding combinators

### ISSUE THREAD

**Issue by rgrinberg** [inhabitedtype/angstrom#66]
Folding versions of various list returning combinators are a very convenient thing. Often, a list is just an intermediate data structure, in which case there's no need to allocate it. One reason why such a combinator is not necessary in attoparsec is because Haskell's lists are lazy. So parsing a list and the folding over it is just as efficient as folding.

The other combinators that should be considered is the stateful scanner:

```
val scan : 's -> ('s -> char -> 's option) -> string t
```

Although in OCaml, there are other ways of making a parser stateful.

**Comment by seliopou** [comment]
Closed by #67, #73.
