### ISSUE TITLE
Entire buffer always 'unconsumed'

### ISSUE THREAD

**Issue by jdjakub** [inhabitedtype/angstrom#75]
Say I have the string `aaaaa`, and I want to parse `aa`. If I use the `Buffered` interface, I do this:
```
let q =
  let (Partial k) = parse (string "aa")
in k (`String "aaaaa")
```
Intuitively, this should consume positions 0, 1 of the buffer and leave positions 2 to 4 unconsumed. But what I get is:
```
val q : string state = Done ({buffer = <abstr>; off = 0; len = 5}, "aa")
```
`off = 0; len = 5` seemingly indicating that the entire buffer was unconsumed, though the desired result is still obtained.
In fact, no matter the input or the parser, I always seem to get `offs = 0; len = <buffer size>`.
This is a problem if I want to keep parsing though the buffer before refilling it from some data source, because after a successful parse it's not clear how to resume where it left off.

**Comment by seliopou** [comment]
Which version of the library are you using? I've tried this one version `0.3.0` and `0.4.0` and I'm getting the expected output on both:

```
#require "angstrom";;
open Angstrom;;

utop # let (Buffered.Partial k) = Buffered.parse (string "aa") in k (`String "aaaaa");;
- : string Buffered.state =
Angstrom.Buffered.Done ({Angstrom.Buffered.buffer = <abstr>; off = 2; len = 3}, "aa") 
utop # Buffered.parse ~input:(`String "aaaaa") (string "aa");;
- : string Buffered.state =
Angstrom.Buffered.Done ({Angstrom.Buffered.buffer = <abstr>; off = 2; len = 3}, "aa")
```

**Comment by jdjakub** [comment]
Ah, I didn't realise I was still using version `0.1.1`.
