### ISSUE TITLE
Compare to other OCaml parser combinator libraries in README

### ISSUE THREAD

**Issue by dsheets** [inhabitedtype/angstrom#9]
In particular, I find `mparser`, `opal`, `planck`, and `p3` (?).

**Comment by seliopou** [comment]
All of them don't support incremental input, a non-blocking interface, or both. I can write some thing up about it on a wiki page. Any other libraries that should be compared, let me know.

**Comment by seliopou** [comment]
Here's a work-in-progress.

... I don't understand what p3 is.

Library | Monadic interface | Unbounded lookahead | Unbuffered, zero-copy interface| Non-blocking incremental interface|Async support | Lwt support |
----------|-------------------------|--------------------------------|-------------------------|--------------------|---|--------------|
Angstrom|Yes|Yes|Yes|Yes|Yes|Yes|
[opal]|Yes|Yes|No|No|No|No|No|
[mparser]|Yes|Yes|No|No|No|No|
[planck][]|Yes|Yes|No|No|No|No|

[mparser]: https://github.com/cakeplus/mparser
[opal]: https://github.com/pyrocat101/opal
[planck]: https://bitbucket.org/camlspotter/planck

**Comment by seliopou** [comment]
If you have any suggestions about features to add to the table, let me know. I'll investigate further tomorrow.

**Comment by seliopou** [comment]
Vertical feature version:

Feature \ Library                   | Angstrom | [opal] | [mparser] | [planck] |
------------------------------------|:--------:|:------:|:---------:|:--------:|
Monadic Interface                   | ✅        | ✅      | ✅         | ✅        |
Unbounded Lookahead                 | ✅        | ✅      | ✅         | ✅        |
Unbuffered (zero-copy) interface    | ✅        | ❌      | ❌         | ❌        |
Non-blocking incremental interface  | ✅        | ❌      | ❌         | ❌        |
Async Support                       | ✅        | ❌      | ❌         | ❌        |
Lwt Support                         | ✅        | ❌      | ❌         | ❌        |
                                                                        
[mparser]: https://github.com/cakeplus/mparser
[opal]: https://github.com/pyrocat101/opal
[planck]: https://bitbucket.org/camlspotter/planck
