### ISSUE TITLE
Readme example defines rchain1 instead of lchain1?

### ISSUE THREAD

**Issue by vogler** [inhabitedtype/angstrom#90]
If I adjust the example in the readme to return `type e = Const of int | Binop of op * e * e`, I get for `eval "1+2+3"` the value `Binop (Add, Const 1, Binop (Add, Const 2, Const 3))` which is right-associative.
What would be the definition for `lchain1`?

**Comment by seliopou** [comment]
You are correct that this implementation is right-associative! My mistake.

I believe the correct implementation of `chainl1` is:

```ocaml
let chainl1 e op =
  let rec go acc =
    (lift2 (fun f x -> f acc x) op e >>= go) <|> return acc in
  e >>= fun init -> go init
```

The helper function `go` is necessary here that one can accumulate parsed expressions and combine them in, essentially, the reverse order in which they're parsed.

I'll change the README later today. Thanks for pointing this out!
