### ISSUE TITLE
Improving error messages

### ISSUE THREAD

**Issue by sgronblo** [inhabitedtype/angstrom#91]
I recently created a small expression parser in a project using `mparser`. I got stuck when I tried to figure out how to define a recursive parser. Somebody recommended me to check out `angstrom` and I found the `fix` combinator which solved my problem perfectly...

However, when I was using mparser I was getting very nice error messages when a parser failed. mparser would show how much of the input had been consumed and what the currently expected chars were. I can't seem to get anything more than "satisfy" to print when my angstrom parsers fail.

Is there anything I can do to improve this situation?

**Comment by dinosaure** [comment]
You can use the `<?>` to _mark_ your parser. Then, when you encounter an error, the `Fail (_, path, msg)` shows you which parser was used (`path`) and the message error. So, `p <?> "parser p"` will put in the `path` `"parser p"` in the case of failure.

See the [documentation](https://github.com/inhabitedtype/angstrom/blob/master/lib/angstrom.mli#L293).

**Comment by sgronblo** [comment]
Thanks I figured this out by myself last night after reading through the library a bit more. Now at least the "marks" message is more readable. However, I am still trying to come up with a good way to see at what point of the input the parser failed. Is there some good way to do that as well?

**Comment by dinosaure** [comment]
The first value of `Fail (unconsumed, _, _)` is the rest of your input _unconsumed_ by your parser. So, `unconsumed.off` is the point where your parser fails 👍 !

**Comment by seliopou** [comment]
@dinosaure thanks for fielding the question! @sgronblo it looks like your questions have been answered, so I'm going to close this issue. However if you still have more questions on the topic, feel free to continue the discussion.

**Comment by sgronblo** [comment]
I tried to avoid writing my own parser run function for a while and just tried to make do with `parse_only` and marking my parsers with `<?>`. However now I have trouble with the "end_of_input" error.

If I understand correctly it should mean that I tried to parse end_of_input, but there was remaining input in the input string. If I use `parse_only` then I only get access to a `Result.result` but in order to pattern match on the `Fail` constructor I would need to run some function that produces a parser state. I tried to replicate the implementation of `parse_only` but with a custom `state_to_result`, however many of the members required are not publically exposed.

I also tried to play a bit with using `Buffered.parse` to get access to the `Buffered.state`, but now it seems I need to deal with manually feeding the parser.

What would be the easiest way to get access to a simple parsing function that gives access to `Buffered.result` instead of `Result.result`?

**Comment by sgronblo** [comment]
In case anyone else is having the same problem I ended up using the Buffered.parse function + Core.Bigstring to print out the unconsumed output like this:

```
let parse_value input_string =
    parse_only value_parser (`String input_string)

let fail_to_string marks err =
    String.concat " > " marks ^ ": " ^ err

let state_to_verbose_result = function
    | Buffered.Partial _ -> Error "incomplete input"
    | Done (_, v) -> Ok v
    | Fail (unconsumed, marks, msg) ->
        let remaining_big_string = (Core.Bigstring.sub unconsumed.buffer ~pos:unconsumed.off ~len:unconsumed.len) in
        let combined_msg = fail_to_string marks msg ^ " with unconsumed: " ^ Core.Bigstring.to_string remaining_big_string in
        Error combined_msg

let parse_query s =
    let initial_parser_state = Buffered.parse ~input:(`String s) query_parser in
    let final_parser_state = Buffered.feed initial_parser_state `Eof in
    state_to_verbose_result final_parser_state
```
