### ISSUE TITLE
Angstrom and js_of_ocaml (or JS in general)

### ISSUE THREAD

**Issue by dinosaure** [inhabitedtype/angstrom#95]
If I follow the start of the TCO with JavaScript [now](https://kangax.github.io/compat-table/es6/#test-proper_tail_calls_(tail_call_optimisation)), we can not believe (yet) than it's possible to use a _large_ (like `ocaml-git`) Angstrom decoder in a JS virtual machine.

`js_of_ocaml` (cc @hhugo) try to optimize some recursive pattern but not all - and specifically some patterns available in Angstrom.

So the solution is to switch Angstrom to a [trampoline pattern](http://c.shld.net/rpx/i/s/i/spin/image/spin_prod_943128812??hei=64&wid=64&qlt=50) like [Decompress](https://github.com/mirage/decompress/blob/master/lib/decompress.ml#L2296) and _break_ the recursion.

Then, it's all about the optimization for a specific back-end. Switch to this kind of recursion can regress the performance for the native back-end but needed for a JS back-end. An idea (from @Armael) it's to _functorize_ ([trampoline](https://i5.walmartimages.com/asr/665da317-7bb8-4715-b055-5763caba07e6_1.d3b6e2516f2c12d841af150000b31356.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF) or [not](https://i.ytimg.com/vi/Wlqy6iBNFII/hqdefault.jpg)?) but the optimization will be not be able to without `flambda`. I did a [patch](https://paste.isomorphis.me/ngc) of Angstrom from the current version to break the recursion.

**Comment by dinosaure** [comment]
`opam pin add angstrom https://github.com/dinosaure/angstrom.git#jsoo` if you want to use it. The current patch has a conflict with some updates - keep in your mind, I break the API.

**Comment by seliopou** [comment]
@dinosaure and I discussed this at ICFP and ran some benchmarks with the patch. At this time, merging the patch incurs too much of a performance regression. So unfortunately, only parses that can be supported by the browser's stack will be supported by angstrom.

**Comment by SGrondin** [comment]
I've ported @dinosaure 's `jsoo` branch to the current master. [Link](https://github.com/SGrondin/angstrom/tree/jsoo). I make no guarantees about its correctness, but it's able to run a large and complex parser in Electron v8 without any issues and without having to make any changes to my code. It's performant enough for my needs.

`opam pin add angstrom https://github.com/SGrondin/angstrom.git#jsoo`

**Comment by seliopou** [comment]
See #187
